### ISSUE TITLE
File not found...

### ISSUE THREAD

**Issue by clicktechnology** [statgenetics/seqspark#10]
Hi Everyone,

I'm trying to get the demo configuration and demo data example running on a 4 node cluster and cannot get it working.  I know the answer is _very_ simple.

The conf file for seqspark looks like this...
```
seqspark {
  project = demo
  localDir = {$PWD}
  pipeline = [ "qualityControl", "association" ]
  input {
    genotype.path = "/user/hadoop/demo/simulated.vcf.bz2"
    phenotype.path = "/user/hadoop/demo/simulated.tsv"
  }
  qualityControl {
    genotypes = ["DP >= 8 and GQ >= 20"]
    variants = ["missingRate <= 0.1"]
    summaries = ["pca", "titv"]
    save = true
    export = true
  }
  association {
    trait {
      list = ["bmi", "disease"]
      bmi {
        binary = false
        covariates = ["sex", "age", "disease"]
        pc = 0
      }
      disease {
        binary = true
        covariates = ["sex", "age", "bmi"]
        pc = 0
      }
    }
    method {
      list = ["skato"]
    }
  }
}
```

The process runs about 41 jobs all told and then begins the pca analysis.  It errors out with the following output from java on the head node.

```
java.io.FileNotFoundException: File file:/home/hadoop/demo/demo/pca.csv does not exist
It is possible the underlying files have been updated. You can explicitly invalidate the cache in Spark by running 'REFRESH TABLE tableName' command in SQL or by recreating the Dataset/DataFrame involved.
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.org$apache$spark$sql$execution$datasources$FileScanRDD$$anon$$readCurrentFile(FileScanRDD.scala:127)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:177)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:101)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The file is there on the head node in the regular file system.

Clearly the answer is to tell seqspark in the demo.conf to use the HDFS when creating the pca.csv file rather than the local file system, so the file appears in ...
```
hdfs:/user/hadoop/demo/demo/pca.csv 
```
instead of..
```
file:/home/hadoop/demo/demo/pca.csv 
```

The solution is a one-liner, like "In the QualityControl section of your conf, add the line...

 ```pca.output.path = "hdfs://user/hadoop/demo/demo/pca.csv"```

Does anyone know how to tell seqspark to output data to the HDFS and not the local filesystem?

Any help warmly received.

Regards,

Morgan

**Comment by zhangdi-devel** [comment]
Hi @clicktechnology ,

   It is designed to output on a local filesystem, but the underlying assumption is every worker can access this file with the same path, which might be violated on some cluster.
   To test if it is the case for your cluster, you can go to the spark scala shell and try to read that file.
   I'll update the code this weekend to fix it. The file will still be output to the local filesystem, but the later use won't need to read that file but to use a cached dataframe in Spark directly.

Di

**Comment by clicktechnology** [comment]
Hi Di,
That's awesome, thanks for the prompt reply.  OK, I get it.  So, on the cluster head node you need to run an nfs share for /home/hadoop.  Every hdfs node/worker mounts that share and then uses it to access the pca.csv data and so the process runs as normal.

I'll set this up now and let you know how it went and then 'Close and comment' to finish the issue.

Thanks again,

Regards,

Morgan

**Comment by clicktechnology** [comment]
Hi Di,

OK, that works.  I set up the head node with nfs and made all the other nodes mount the exported /home/hadoop folder and re-ran the job.   Went all the way through first time.

Thanks for the help!

Cheers,

Morgan

To summarise for other users : In the seqspark setup, you need two shared filesystems.  They are..

- HDFS/Hadoop which is on all nodes and is used for essentially distributing huge files to all nodes.  

- An nfs/samba mount on your head node which all nodes connect to and it serves all the small files like .confs, .csvs and the final results files too.
