### ISSUE TITLE
Issues while running on Hadoop cluster

### ISSUE THREAD

**Issue by tushu1232** [statgenetics/seqspark#4]
[root@hpcsrcn01 bin]# ./seqspark /demo.conf 
conf file:       /demo.conf
spark options:   
Exception in thread "main" com.typesafe.config.ConfigException$Parse: reference.conf: 5: Key 'dbDir_unset' may not be followed by token: 'annotation' (if you intended 'annotation' to be part of the value for 'dbDir_unset', try enclosing the value in double quotes)
	at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:435)
	at com.typesafe.config.impl.Parser$ParseContext.parseError(Parser.java:431)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:786)
	at com.typesafe.config.impl.Parser$ParseContext.parseValue(Parser.java:520)
	at com.typesafe.config.impl.Parser$ParseContext.parseObject(Parser.java:803)
	at com.typesafe.config.impl.Parser$ParseContext.parse(Parser.java:993)
	at com.typesafe.config.impl.Parser.parse(Parser.java:34)
	at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:222)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:602)
	at com.typesafe.config.impl.Parseable$ParseableResources.rawParseValue(Parseable.java:554)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:176)
	at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:170)
	at com.typesafe.config.impl.Parseable.parse(Parseable.java:227)
	at com.typesafe.config.impl.ConfigImpl$1.call(ConfigImpl.java:368)
	at com.typesafe.config.impl.ConfigImpl$1.call(ConfigImpl.java:365)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:58)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:86)
	at com.typesafe.config.impl.ConfigImpl.defaultReference(ConfigImpl.java:365)
	at com.typesafe.config.ConfigFactory.defaultReference(ConfigFactory.java:423)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:202)
	at com.typesafe.config.ConfigFactory.loadDefaultConfig(ConfigFactory.java:245)
	at com.typesafe.config.ConfigFactory.access$000(ConfigFactory.java:38)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:378)
	at com.typesafe.config.ConfigFactory$1.call(ConfigFactory.java:375)
	at com.typesafe.config.impl.ConfigImpl$LoaderCache.getOrElseUpdate(ConfigImpl.java:58)
	at com.typesafe.config.impl.ConfigImpl.computeCachedConfig(ConfigImpl.java:86)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:375)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:299)
	at com.typesafe.config.ConfigFactory.load(ConfigFactory.java:288)
	at org.dizhang.seqspark.SeqSpark$.readConf(SeqSpark.scala:78)
	at org.dizhang.seqspark.SeqSpark$.main(SeqSpark.scala:47)
	at org.dizhang.seqspark.SeqSpark.main(SeqSpark.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by zhangdi-devel** [comment]
Hi, 

   Are you running seqspark from the source code directory? Can you please pull the latest code and run the install script? Please choose a prefix that is different from the source code director.

Di
