### ISSUE TITLE
trouble downloading seqspark and I cant find seqspark.jar

### ISSUE THREAD

**Issue by dhynasah** [statgenetics/seqspark#6]
I am having trouble downloading and building seqspark. The error I keep getting is SeqSpark.jar is not found. So If you can send me the file that would be great. Or let me know what I am doing wrong. 
this is the error: 
./install --prefix ~/software/seqspark --db-dir /jamesdh/691_project/seqspark
Use of uninitialized value $prefix in string eq at ./install line 34.
Use of uninitialized value $prefix in concatenation (.) or string at ./install line 43.
Use of uninitialized value $prefix in concatenation (.) or string at ./install line 53.
Will install into , database files will be downloaded to /jamesdh/691_project/seqspark
Building seqspark ...
sh: sbt: command not found
Finished building seqspark.
Cannot find target/scala-2.11/SeqSpark.jar, compiling failed? at ./install line 84, <$fh> line 48.
[jamesdh@dc01 seqspark]$ ./install seqspark-db
Use of uninitialized value $ENV{"USR"} in concatenation (.) or string at ./install line 48.
No db-dir specified, will use /user//seqspark.
Building seqspark ...
sh: sbt: command not found
Finished building seqspark.
Cannot find target/scala-2.11/SeqSpark.jar, compiling failed? at ./install line 84, <$fh> line 48.
[jamesdh@dc01 seqspark]$ ^C
[jamesdh@dc01 seqspark]$ dnf reinstall sbt
-bash: dnf: command not found
[jamesdh@dc01 seqspark]$ which sbt
which: no sbt in (/usr/local/sbin:/usr/local/bin:/usr/bin:/lab/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)

**Comment by zhangdi-devel** [comment]
Hi @dhynasah 
  I saw two problems here. 
  First, you don't have `sbt` on your machine. Could you please download it here: https://www.scala-sbt.org/ 
  Second, the `$prefix` not initialized issue. May I know what OS/Distro and version are you using? The install script is just a perl script. Could you show me the perl version: `perl --version`.

Di

**Comment by dhynasah** [comment]
I am quite new to this. I am running this on my school account virtually through putty and I simulated a cluster through the school machines.  and I was just following your tutorial. https://statgenetics.github.io/seqspark/. 
so are you saying I should use a different version of the script?

**Comment by zhangdi-devel** [comment]
I mean I am not sure if the OS or the Perl version cause the `$prefix` issues. The script should work on most Linux distros with any Perl 5. So I want to know if you are using a mainstream Linux and Perl 5.
If you're working on a school cluster, you can ask the admin about the system/Perl versions, and if they can help you install the prerequisites.

**Comment by dhynasah** [comment]
Ok, Finally I got someone to reply at my school. The problem was they did not have sbt installed on the global system. They added it and then I was able to install seqspark. I did get a few warnings when it was installing because of the prefix errors. They didn't really answer my questions about that. but I think for the most part it's fine. thanks for the help!

**Comment by dhynasah** [comment]
Hi. So I am having trouble again. I had to skip over a few of the things in the tutorial. The reason in that my school doesn't have Hadoop installed. They have a "hadoop like system". in order to run my files on all of the spark nodes I launch spark first, and then run the file. But I am having trouble because I cannot use the Seqspark commands. I am in the directory where the demo.conf file is. So is there a way for me to configure my environment to have these commands? Any help you could provide will be greatly appreciated.

**Comment by zhangdi-devel** [comment]
Have you added this line to your `~/.bashrc`:
`export PATH=~/software/seqspark/bin:$PATH`

After doing this, execute `bash` or re-login.

**Comment by dhynasah** [comment]
Thanks! I definitely got somewhere. The commands are being recognized.  But I am now getting another error. 
**Error: seqspark no longer takes run mode option, please check the latest document.
Usage: seqspark conf [opts]
  conf -- File containing the parameters
  opts -- Spark options**
what do I do in this situation?

**Comment by zhangdi-devel** [comment]
Sorry about that. I guess you are trying to run the `SingleStudy` mode here. Just remove `SingleStudy` from the command line. I'll update the doc accordingly.

**Comment by dhynasah** [comment]
Thanks. That helped. I was able to get a little bit further. Although I keep running into more problems. 
This is the error I am getting now: 
[jamesdh@dc01 seqspark_files]$ seqspark demo.conf
conf file:       demo.conf
**spark options:
19/04/05 12:27:49 WARN util.NativeCodeLoader: Unable to load native-hadoop libra                          ry for your platform... using builtin-java classes where applicable
19/04/05 12:27:49 WARN internal.Logging$class: Local jar /home/jamesdh/seqspark/                          SeqSpark.jar does not exist, skipping.
19/04/05 12:27:49 WARN internal.Logging$class: Failed to load org.dizhang.seqspa                          rk.SeqSpark.
java.lang.ClassNotFoundException: org.dizhang.seqspark.SeqSpark
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubm                          it$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167                          )
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scal                          a:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)**


it doesn't make sense because the SesSpark.jar file is here. Should I specify the path or something...although im not sure how to do that. 
and then the org.dizhand.seqspark.SeqSpark...i dont know what that error means. im not sure if that is supposed to be a file, or if its something else... i looked for it and couldn't find it.

**Comment by zhangdi-devel** [comment]
I noticed an extra space between `${SPARK_HOME}` and `SeqSpark.jar`. Could you check the seqspark script? It is a bash script located at `${SPARK_HOME}/bin`. If you are not certain, run this command and paste the output: `cat $(which seqspark)`

**Comment by dhynasah** [comment]
#!/usr/bin/env bash

Usage() {
        echo "Usage: seqspark conf [opts]                  "
        echo "  conf -- File containing the parameters     "
        echo "  opts -- Spark options                      "
}

if [[ -z $1 ]]
then
        echo "Error: you must specify the conf file"
        Usage
        exit
fi

if [ "$1" == "SingleStudy" ] || [ "$1" == "MetaAnalysis" ]
then
        echo "Error: seqspark no longer takes run mode option, please check the latest document."
        Usage
        exit
fi

Conf=$1
shift
Opts=$@


if [ -z $SEQSPARK_HOME ]
then
        SEQSPARK_HOME=$(dirname $(dirname $0))
fi
CONFDIR=${SEQSPARK_HOME}/conf


echo "conf file:       $Conf"
echo "spark options:   $Opts"

spark-submit --driver-class-path $CONFDIR\
    --class org.dizhang.seqspark.SeqSpark $Opts \
    $SEQSPARK_HOME/SeqSpark.jar $Conf

exit 0

**Comment by zhangdi-devel** [comment]
Looks fine. This script does nothing but prepares the `classpath` for java. Could you try to run the command manually like this:
`spark-submit --driver-class-path /home/jamesdh/seqspark/conf --class org.dizhang.seqspark.SeqSpark /home/jamesdh/seqspark/SeqSpark.jar demo.conf`

**Comment by dhynasah** [comment]
I tried it and I am still getting the same error. should I reinstall spark? maybe that's the problem. Also I moved my spark into the seqspark directory because the spark submit commands were not recognized in that directory. and then I added this to my bash file: 
export PATH=~/seqspark/spark/bin:$PATH

but this was before I had the current error.

**Comment by zhangdi-devel** [comment]
I'm not sure if you can move around Spark. Also, Spark should be installed and configured on both the master node and the worker nodes. If all you want is to find the spark-submit, you can just add the Spark bin to `PATH` like this: `export PATH=/path/to/spark/bin:$PATH`.

For seqspark, could you check this: `ls /home/jamesdh/seqspark/SeqSpark.jar`. Or `cd /home/jamesdh/seqspark` and `ls` to check if the `SeqSpark.jar` file is still there.

**Comment by zhangdi-devel** [comment]
Are you using this on a single machine or in a cluster? I'll try to build a docker image for testing purposes later.

**Comment by dhynasah** [comment]
oh, shoot ok. I'll move spark back to its original location. it's on a cluster.  with 24 nodes. Ok let me try some of the things you suggested. and I will get back to you.

**Comment by dhynasah** [comment]
ok. so i am getting no such file or directory for the SeqSpark.jar file. and Then I decided to just check spark to see if its running properly. and im not sure that it is... I dont think so. I ran this wordcount.py script i wrote for a homework assignment a while ago. But I think moving around the directory might have screwed things up.   An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext....definitely something is wrong here. And it ended up shutting itself down without printing out the output.

**Comment by dhynasah** [comment]
I did ls /home/jamesdh/seqspark/target/scala-2.11 
seqSpark.jar is in this directory.... so im not sure whats going on. and why i couldn't find it earlier.

**Comment by zhangdi-devel** [comment]
Have you successfully run the install script? You cannot use the source code directory as the prefix.
The source code and the installed software must be in different places.
If you git cloned seqspark to /home/jamesdh/seqspark, you must use another place for the prefix, and add the installed place to PATH.
For exmaple, if you `install --prefix /home/jamesdh/software/seqspark ...`, you should `export PATH=/home/jamesdh/software/seqspark/bin:$PATH`

**Comment by zhangdi-devel** [comment]
Trying to run the `seqspark` script in the source code directory will lead to the `SeqSpark.jar` Not Found error. And It will be invoked if you accidentally exported the source code bin directory to PATH.

I'll update the tutorial about this.

**Comment by dhynasah** [comment]
> Have you successfully run the install script? You cannot use the source code directory as the prefix.
> The source code and the installed software must be in different places.
> If you git cloned seqspark to /home/jamesdh/seqspark, you must use another place for the prefix, and add the installed place to PATH.
> For exmaple, if you `install --prefix /home/jamesdh/software/seqspark ...`, you should `export PATH=/home/jamesdh/software/seqspark/bin:$PATH`

Yes. I did run the install script. After the admin added sbt.  
second, I created a directory called seqspark_files. its not directly in the source code directory but it is in the seqspark directory.  `/home/jamesdh/seqspark/seqspark_files`. Where should I run it instead?

**Comment by zhangdi-devel** [comment]
You mean you've used `--prefix /home/jamesdh/seqspark/seqspark_files`? Then you need to `export PATH=/home/jamesdh/software/seqspark/seqspark_files/bin:$PATH`. The script `seqspark` will just try to find the `SeqSpark.jar` in its parent folder.

**Comment by dhynasah** [comment]
no matter what I do I still get the same error. if i use `export PATH=~/seqspark/bin:$PATH` or if i use `export PATH=~/home/jamesdh/seqspark/bin:$PATH`.
when I use the latter the seqspark command is not recognized.  I can run it in the parent directory or in any subdirectories and I still get the same error. 
I tried placing `export PATH=~/home/jamesdh/seqspark/target/scala-2.11:$PATH` into my bash file. and I still get the same error. 
I also tried `export PATH=~/seqspark/target/scala-2.11:$PATH`. that didn't work either. 
Thanks for all of your help. Honestly, I appreciate it.

**Comment by dhynasah** [comment]
I also added export PATH=~/seqspark:$PATH.

**Comment by dhynasah** [comment]
So I added `export PATH=~/seqspark/bin:$PATH`

this is what i get back when I echo $PATH
**/home/jamesdh/seqspark:/home/jamesdh/spark/sbin:/home/jamesdh/spark/bin:/home/jamesdh/seqspark/bin:/home/jamesdh/seqspark/target/scala-2.11:/home/jamesdh/spark/sbin:/home/jamesdh/spark/bin:/home/jamesdh/seqspark/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/lab/bin:/opt/cuda/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl**

**Comment by dhynasah** [comment]
Ok, I ended up moving the SeqSpark.jar to the main seqspark directory and out of the target/scala_2.11 directory. and now it seems to work a little better. 
now I'm getting this error: 
**Exception in thread "main" com.typesafe.config.ConfigException$Parse: reference.                                  conf: 5: Key 'dbDir_unset' may not be followed by token: 'annotation' (if you intended 'annotation' to be part of the value for 'dbDir_unset', try enclosing the                                   value in double quotes)**

it will still run, but I am not getting an output folder. 
I am assuming this means I did something wrong in the demo.conf file. I will double check that and make sure I didn't miss something from the tutorial.

**Comment by zhangdi-devel** [comment]
Sorry for not being clear enough. Could you please tell me where your source code is and what you used for `--prefix`? The problem is the `seqspark` script in the source code bin folder should never be called directly.
Then could you try to start over again?
1. Clear the PATH, remove the lines you did for seqspark and re-login;
2. Make sure the source code of seqspark is in some folder. e.g. `~/software/seqspark`
3. run the `install` script with some `--prefix`. This prefix shouldn't be the source code path. That means if your source code is in `~/software/seqspark`, you must use another path for the prefix which will become your `$SEQSPARK_HOME`. e.g. `~/seqspark`
4. Export the PATH env variable: `export PATH=~/seqspark/bin:$PATH` if your prefix is `~/seqspark`.

Notes:
1. Do not use the source code path as the prefix. Actually, you'll see error messages if you do so.
2. If you installed the source code to the prefix without a problem, you don't need to move the built jar file around. The install script does something else (sets up the conf) besides copy the jar and bash script to the prefix.
3. Remove the source code bin dir from PATH. 

Let me know if you still have any difficulties.

**Comment by dhynasah** [comment]
yes. I remember. last time I downloaded this I didn't use --prefix because --prefix was not one of the available options. I can't remember exactly how I did it. But I think I just skipped that and used install and only one path. Now I understand where I went wrong. That's been the source of all of my problems.  
These are the options given for install: 
`This install program copies files (often just compiled) into destination
locations you choose.  If you want to download and install a ready-to-use
package on a GNU/Linux system, you should instead be using a package manager
like yum(1) or apt-get(1).

In the first three forms, copy SOURCE to DEST or multiple SOURCE(s) to
the existing DIRECTORY, while setting permission modes and owner/group.
In the 4th form, create all components of the given DIRECTORY(ies).

Mandatory arguments to long options are mandatory for short options too.
      --backup[=CONTROL]  make a backup of each existing destination file
  -b                  like --backup but does not accept an argument
  -c                  (ignored)
  -C, --compare       compare each pair of source and destination files, and
                        in some cases, do not modify the destination at all
  -d, --directory     treat all arguments as directory names; create all
                        components of the specified directories
  -D                  create all leading components of DEST except the last,
                        or all components of --target-directory,
                        then copy SOURCE to DEST
  -g, --group=GROUP   set group ownership, instead of process' current group
  -m, --mode=MODE     set permission mode (as in chmod), instead of rwxr-xr-x
  -o, --owner=OWNER   set ownership (super-user only)
  -p, --preserve-timestamps   apply access/modification times of SOURCE files
                        to corresponding destination files
  -s, --strip         strip symbol tables
      --strip-program=PROGRAM  program used to strip binaries
  -S, --suffix=SUFFIX  override the usual backup suffix
  -t, --target-directory=DIRECTORY  copy all SOURCE arguments into DIRECTORY
  -T, --no-target-directory  treat DEST as a normal file
  -v, --verbose       print the name of each directory as it is created
      --preserve-context  preserve SELinux security context
  -Z                      set SELinux security context of destination
                            file and each created directory to default type
      --context[=CTX]     like -Z, or if CTX is specified then set the
                            SELinux or SMACK security context to CTX
      --help     display this help and exit
      --version  output version information and exit

The backup suffix is '~', unless set with --suffix or SIMPLE_BACKUP_SUFFIX.
The version control method may be selected via the --backup option or through
the VERSION_CONTROL environment variable.  Here are the values:

  none, off       never make backups (even if --backup is given)
  numbered, t     make numbered backups
  existing, nil   numbered if numbered backups exist, simple otherwise
  simple, never   always make simple backups

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation at: <https://www.gnu.org/software/coreutils/install>
`

**Comment by dhynasah** [comment]
i tired: 
`install -t ~/software/seqspark --db-dir /home/jamesdh/seqspark`
--db-dir is not recognized either.

**Comment by dhynasah** [comment]
So, I ended up just completely starting over. When you say, make sure the source code is in the same folder, what do you mean? the same folder as what? 
then i should run the install script with some prefix. so should i run it as :
` seqspark$ ./install --prefix ~/software/seqspark --db-dir /home/jamesdh/seqspark
`
because when I do this it says seqspark$ command not found...
if i do just `./install --prefix ~/software/seqspark --db-dir /home/jamesdh/seqspark`
then it says install: no such file or directory. 
Is it possible for me to give you my login so you can figure it out? I can give you my email address. 
I am really desperate to just have this working properly.

**Comment by zhangdi-devel** [comment]
It's "some" folder not "same".

no problem, I can help you install it. 
But make sure just email me a temporary login cred so that you can change after I finish.

zhangdi.devel[at]gmail.com

**Comment by dhynasah** [comment]
I sent you an email. my email is mauricia-james16@live.com
